name: Update Calendar

on:
  push:
    branches: [ main ]
    paths: [ 'events.json' ]
  workflow_dispatch:

jobs:
  generate-ical:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Generate iCal file
      run: node generate-ical.js
      
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add calendar.ics
        git diff --staged --quiet || git commit -m "Auto-update calendar.ics"
        git push
